name: Deploy
# Deploys the website whenever changes are merged to main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  checks:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    permissions:
      checks: read # Required for lewagon/wait-on-check-action

    steps:
      - name: Wait for checks to pass
        uses: lewagon/wait-on-check-action@ccfb013c15c8afb7bf2b7c028fb74dc5a068cccc # v1.3.4
        with:
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: checks
          allowed-conclusions: success

  deploy:
    needs: checks

    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.WEBSITE_URL }}

    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          password: ${{ secrets.SCP_PASSWORD }}
          source: dist/*
          strip_components: 1
          target: ${{ secrets.SCP_TARGET }}
          rm: true
