name: Deploy
# Deploys the website when new changes pass validation on main

on:
  workflow_run:
    workflows: ["Validate"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    # Only deploy if validation succeeds (or manually triggered)
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.WEBSITE_URL }}

    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          password: ${{ secrets.SCP_PASSWORD }}
          source: "dist/*"
          strip_components: 1
          target: ${{ secrets.SCP_TARGET }}
          rm: true
