name: Deploy
# Deploys the website whenever changes are merged to main

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.WEBSITE_DOMAIN }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "dist/*"
          target: ${{ secrets.SSH_PATH }}
          rm: true
