name: Website status
# Checks whether the website is active and working on a regular schedule

on:
  schedule:
    - cron: 0 0 * * * # Once a day
  workflow_dispatch:

permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.WEBSITE_URL }}

    steps:
      - name: Request website
        run: curl ${{ vars.WEBSITE_URL }}
